/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reader.java
 *
 * Created on 15/Nov/2010, 15:52:34
 */

package GUI.employees;

import DataStructures.Person;
import com.toedter.calendar.JCalendar;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.GregorianCalendar;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import librarynetbeans.Constants;
import librarynetbeans.Validation;

/**
 *
 * @author LG
 */
public class Employees extends javax.swing.JPanel implements
			PropertyChangeListener {

    /** Creates new form Reader */
    public Employees() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BirthdayTextEmp1 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        BirthdayTextEmp2 = new javax.swing.JFormattedTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        fireButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        FindButtonEmp = new javax.swing.JButton();
        BirthDate1Emp = new javax.swing.JButton();
        BirthDate2Emp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        FindButtonEmp1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        getInfoButton = new javax.swing.JButton();
        clearFieldsButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Find Employee:");

        jLabel2.setText("Name:");

        jLabel3.setText("Birthday:");

        BirthdayTextEmp1.setText("   /   /   ");
        BirthdayTextEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthdayTextEmp1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("New Employee:");

        jLabel5.setText("Name:");

        jLabel6.setText("Address:");

        jLabel7.setText("Birthday");

        jLabel9.setText("ID Card Number:");

        jLabel10.setText("Contact:");

        jLabel11.setText("E-mail address:");

        BirthdayTextEmp2.setText("   /   /   ");
        BirthdayTextEmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthdayTextEmp2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        fireButton.setText("Fire");
        fireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Change Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Return");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("List All Employees");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        FindButtonEmp.setText("Find");
        FindButtonEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButtonEmpActionPerformed(evt);
            }
        });

        BirthDate1Emp.setText("Choose Date");
        BirthDate1Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDate1EmpActionPerformed(evt);
            }
        });

        BirthDate2Emp.setText("Choose Date");
        BirthDate2Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDate2EmpActionPerformed(evt);
            }
        });

        jLabel12.setText("Order By:");

        FindButtonEmp1.setText("Find");
        FindButtonEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButtonEmp1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "ID" }));

        getInfoButton.setText("Get Info");
        getInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getInfoButtonActionPerformed(evt);
            }
        });

        clearFieldsButton.setText("Clear Fields");
        clearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsButtonActionPerformed(evt);
            }
        });

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Password: ");

        jLabel14.setText("Confirm Password:");

        jButton6.setText("List Active Employees");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BirthdayTextEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BirthDate1Emp)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FindButtonEmp)
                                    .addComponent(FindButtonEmp1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton4)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel13))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(BirthdayTextEmp2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BirthDate2Emp)
                                                .addGap(204, 204, 204))
                                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearFieldsButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(getInfoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fireButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(FindButtonEmp1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(BirthdayTextEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthDate1Emp)
                            .addComponent(FindButtonEmp))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BirthdayTextEmp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(BirthDate2Emp))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(clearFieldsButton)
                            .addComponent(jButton3)
                            .addComponent(jButton6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton4))
                    .addComponent(getInfoButton)
                    .addComponent(fireButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Constants.employeesMenu.setVisible(false);
        Constants.mainMenu.setVisible(true);
        Constants.frame.setContentPane(Constants.mainMenu);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO We have to protect against wrong input. Also, maybe complete birthday and stuff.

        String nome, morada, eMail, telefone, bi;

        nome = jTextField2.getText();
        morada = jTextField3.getText();
        bi = jTextField4.getText();
        telefone = jTextField6.getText();
        eMail = jTextField5.getText();

        int [] date = Validation.checkInsertedDate(BirthdayTextEmp2.getText(), false);

        if (jPasswordField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty password field...");
        }
        else if(!jPasswordField1.getText().equals(jPasswordField2.getText()))
        {
            JOptionPane.showMessageDialog(this, "Passwords do not match...");
        }
        else{
            if(!nome.equals("") && !morada.equals("") &&  Validation.isInteger(bi)
                            && (!telefone.equals("") && Validation.isInteger(telefone) || telefone.equals("")) && date!=null){
                int value = Constants.dbhandler.addPerson(nome, morada, bi, telefone, eMail, date, true, jPasswordField1.getText());

                if (value >= 0){
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField6.setText("");
                    jTextField5.setText("");
                    BirthdayTextEmp2.setText("");
                    JOptionPane.showMessageDialog(this, "Employee added successfully, with ID: " + value + "!");
                }
                else if(value == -1)
                {
                    JOptionPane.showMessageDialog(this, "There's already an employee with such ID Card number!");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Employee couldn't be added to the database...");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Invalid data");
            }
        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        ArrayList <Person> list = Constants.dbhandler.getPersonsList(true, orderBy, true);

        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();

        for (int i = 0; i < list.size(); i++){
            String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
            model.addElement(info);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void FindButtonEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonEmpActionPerformed
         String orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        int [] date = Validation.checkInsertedDate(BirthdayTextEmp1.getText(), false);

          if(date==null){
              JOptionPane.showMessageDialog(this, "Invalid date");
          } else {
            ArrayList <Person> list = Constants.dbhandler.findPersonByBirthDate(date,true,orderBy);

            DefaultListModel model = (DefaultListModel) jList1.getModel();
            model.clear();

            for (int i = 0; i < list.size(); i++){
                String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
                model.addElement(info);
            }
          }
    }//GEN-LAST:event_FindButtonEmpActionPerformed

    private void BirthdayTextEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthdayTextEmp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthdayTextEmp1ActionPerformed

    private void BirthDate1EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDate1EmpActionPerformed
        JFrame date = new JFrame("Choose Date");
        birthDate1EmpList = new JCalendar();

        date.getContentPane().add(birthDate1EmpList);
        date.pack();
        date.setVisible(true);
        birthDate1EmpList.addPropertyChangeListener(this);
    }//GEN-LAST:event_BirthDate1EmpActionPerformed

    private void BirthDate2EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDate2EmpActionPerformed
        JFrame date = new JFrame("Choose Date");
        birthDate2EmpList = new JCalendar();

        date.getContentPane().add(birthDate2EmpList);
        date.pack();
        date.setVisible(true);
        birthDate2EmpList.addPropertyChangeListener(this);
    }//GEN-LAST:event_BirthDate2EmpActionPerformed

    private void BirthdayTextEmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthdayTextEmp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthdayTextEmp2ActionPerformed

    private void FindButtonEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonEmp1ActionPerformed
        //TODO: Protecções
        String orderBy;

        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Invalid name");
        } else {

            orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
            ArrayList <Person> list = Constants.dbhandler.findEmployeeByName(jTextField1.getText(), orderBy);

            DefaultListModel model = (DefaultListModel) jList1.getModel();
            model.clear();

            for (int i = 0; i < list.size(); i++){
                String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
                model.addElement(info);
            }
        }
    }//GEN-LAST:event_FindButtonEmp1ActionPerformed

    //TODO alterar este método se a listagem for modificada
    private void getInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getInfoButtonActionPerformed
        String value = ((String)jList1.getSelectedValue());

        if(value!=null){
            clearFieldsButtonActionPerformed(null);
            String [] splitted = value.split(" ");
            ArrayList<String> array = Constants.dbhandler.getEmployeeById(splitted[splitted.length-1]);
            if(array!=null){
                jTextField2.setText(array.get(0));
                jTextField3.setText(array.get(1));
                BirthdayTextEmp2.setText(array.get(2));
                jTextField4.setText(array.get(3));
                jTextField4.setEditable(false);
                jTextField6.setText(array.get(4));
                jTextField5.setText(array.get(5));
            } else {
                JOptionPane.showMessageDialog(this, "Something went wrong. Please contact your support!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must select an employee on the right side!");
        }
    }//GEN-LAST:event_getInfoButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome, morada, eMail, telefone, bi;

        nome = jTextField2.getText();
        morada = jTextField3.getText();
        bi = jTextField4.getText();
        telefone = jTextField6.getText();
        eMail = jTextField5.getText();

        int [] date = Validation.checkInsertedDate(BirthdayTextEmp2.getText(), false);

        if(!nome.equals("") && !morada.equals("") &&  Validation.isInteger(bi)
                        && (!telefone.equals("") && Validation.isInteger(telefone) || telefone.equals("")) && date!=null){
            if(Constants.dbhandler.changePersonData(nome, morada, bi, telefone, eMail, date, true)){
                JOptionPane.showMessageDialog(this, "Changes made successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Something went Wrong");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Data");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsButtonActionPerformed
            jTextField2.setText("");
            jTextField3.setText("");
            BirthdayTextEmp2.setText("  /  /    ");
            jTextField4.setText("");
            jTextField4.setEditable(true);
            jTextField6.setText("");
            jTextField5.setText("");
            ((DefaultListModel) jList1.getModel()).clear();
            jPasswordField1.setText("");
            jPasswordField2.setText("");
            
    }//GEN-LAST:event_clearFieldsButtonActionPerformed

    private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
        String value = ((String)jList1.getSelectedValue());

        if(value!=null){
            //clearFieldsButtonActionPerformed(null);
            String [] splitted = value.split(" ");
            ArrayList<String> array = Constants.dbhandler.getEmployeeById(splitted[splitted.length-1]);
            if(array!=null){
                jTextField2.setText(array.get(0));
                jTextField3.setText(array.get(1));
                BirthdayTextEmp2.setText(array.get(2));
                jTextField4.setText(array.get(3));
                jTextField4.setEditable(false);
                jTextField6.setText(array.get(4));
                jTextField5.setText(array.get(5));

                int opt = JOptionPane.showOptionDialog(this, "Are you sure that you want fire this employee?",
                        "Fire Cliente", 2, 2, null, new String [] {"Yes","No"}, 1);

                //yes option == 0 | no option == 1
                if(opt==0){
                    int retVal=Constants.dbhandler.fireEmployee(jTextField4.getText());

                    if(retVal==-3){
                         JOptionPane.showMessageDialog(this, "This employee was already fired");
                         clearFieldsButtonActionPerformed(null);
                    } else if (retVal <=0 ){
                        JOptionPane.showMessageDialog(this, "Something went wrong. Please contact your support! error:"+retVal);
                    } else if( retVal==1) {
                        JOptionPane.showMessageDialog(this, "Employee fired!");
                        clearFieldsButtonActionPerformed(null);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Something went wrong. Please contact your support!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must select an employee on the right side!");
        }
    }//GEN-LAST:event_fireButtonActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        ArrayList <Person> list = Constants.dbhandler.getPersonsList(true, orderBy, false);

        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();

        for (int i = 0; i < list.size(); i++){
            String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
            model.addElement(info);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public void propertyChange(PropertyChangeEvent evt) {
        Object source = evt.getSource();
        Calendar cal;
        GregorianCalendar cal1;
        if (source == birthDate1EmpList) {
                cal = birthDate1EmpList.getCalendar();
                cal1 = new GregorianCalendar(cal.get(Calendar.YEAR),
                                cal.get(Calendar.MONTH), cal.get(Calendar.DAY_OF_MONTH));
                BirthdayTextEmp1.setText(cal1.get(Calendar.DAY_OF_MONTH) + "/"
                                + (cal1.get(Calendar.MONTH)+1) + "/"
                                + cal1.get(Calendar.YEAR));

        }
        else if (source == birthDate2EmpList) {
                cal = birthDate2EmpList.getCalendar();
                cal1 = new GregorianCalendar(cal.get(Calendar.YEAR),
                                cal.get(Calendar.MONTH), cal.get(Calendar.DAY_OF_MONTH));
                BirthdayTextEmp2.setText(cal1.get(Calendar.DAY_OF_MONTH) + "/"
                                + (cal1.get(Calendar.MONTH)+1) + "/"
                                + cal1.get(Calendar.YEAR));

        }
        /*
         * else if( source == OUTRO JCALENDAR)....
         */

    }

    // TODO o que e isto? Nao sera para apagar?
    // This method returns the selected radio button in a button group
    public static JRadioButton getSelectionEmployees(ButtonGroup group) {

        if (group != null)
            System.out.println("Hello");
    for (Enumeration e=group.getElements(); e.hasMoreElements(); ) {
        JRadioButton b = (JRadioButton)e.nextElement();
        if (b.getModel() == group.getSelection()) {
            return b;
        }
    }
        return null;
    }
    
    private ButtonGroup orderGroup = new ButtonGroup();
    private JCalendar birthDate1EmpList;
    private JCalendar birthDate2EmpList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BirthDate1Emp;
    private javax.swing.JButton BirthDate2Emp;
    private javax.swing.JFormattedTextField BirthdayTextEmp1;
    private javax.swing.JFormattedTextField BirthdayTextEmp2;
    private javax.swing.JButton FindButtonEmp;
    private javax.swing.JButton FindButtonEmp1;
    private javax.swing.JButton clearFieldsButton;
    private javax.swing.JButton fireButton;
    private javax.swing.ButtonGroup genreGroup;
    private javax.swing.JButton getInfoButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
