/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame.java
 *
 * Created on 17/Nov/2010, 13:44:17
 */

package librarynetbeans;
import GUI.Login;
import GUI.MainMenu;
import GUI.documents.Document;
import GUI.employees.Employees;
import GUI.readers.Reader;

/**
 *
 * @author LG
 */
public class Frame extends javax.swing.JFrame {

    /** Creates new form Frame */
    public Frame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frame frame = new Frame();

                Login login = new Login();
                MainMenu mainMenu = new MainMenu();
                Document doc = new Document();
                Employees emp = new Employees();
                Reader reader = new Reader();

                login.setVisible(true);
                mainMenu.setVisible(false);
                doc.setVisible(false);
                emp.setVisible(false);
                reader.setVisible(false);

                new Constants(login, mainMenu, doc, emp, reader, frame);

                frame.setContentPane(Constants.loginMenu);
                frame.setTitle("Library");
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
