/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reader.java
 *
 * Created on 15/Nov/2010, 15:52:34
 */

package GUI.readers;

import DataStructures.Person;
import com.toedter.calendar.JCalendar;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import librarynetbeans.Constants;
import librarynetbeans.Validation;

/**
 *
 * @author LG
 */
public class Reader extends javax.swing.JPanel implements
			PropertyChangeListener {

    /** Creates new form Reader */
    public Reader() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateText1Reader = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        dateText2Reader = new javax.swing.JFormattedTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        chooseDate1Emp = new javax.swing.JButton();
        chooseDate2Emp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        clearFieldsButton = new javax.swing.JButton();
        getInfoButton = new javax.swing.JButton();
        findReaderByNameButton = new javax.swing.JButton();
        findReaderByDateButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Find Reader:");

        jLabel2.setText("Name:");

        jLabel3.setText("Birthday:");

        dateText1Reader.setText("   /   /   ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("New Reader:");

        jLabel5.setText("Name:");

        jLabel6.setText("Address:");

        jLabel7.setText("Birthday");

        jLabel9.setText("ID Card Number:");

        jLabel10.setText("Contact:");

        jLabel11.setText("E-mail address:");

        dateText2Reader.setText("   /   /   ");

        jList1.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Exclude");

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Change Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Return");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("List Readers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        chooseDate1Emp.setText("Choose Date");
        chooseDate1Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDate1EmpActionPerformed(evt);
            }
        });

        chooseDate2Emp.setText("Choose Date");
        chooseDate2Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDate2EmpActionPerformed(evt);
            }
        });

        jLabel12.setText("Order By:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "ID" }));

        clearFieldsButton.setText("Clear Fields");
        clearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsButtonActionPerformed(evt);
            }
        });

        getInfoButton.setText("Get Info");
        getInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getInfoButtonActionPerformed(evt);
            }
        });

        findReaderByNameButton.setText("Find");
        findReaderByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findReaderByNameButtonActionPerformed(evt);
            }
        });

        findReaderByDateButton.setText("Find");
        findReaderByDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findReaderByDateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jButton4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(dateText1Reader, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chooseDate1Emp))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(findReaderByNameButton)
                                    .addComponent(findReaderByDateButton))
                                .addGap(25, 25, 25))
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateText2Reader, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooseDate2Emp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearFieldsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(getInfoButton))
                            .addComponent(jButton3))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(547, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(dateText1Reader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chooseDate1Emp))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(findReaderByDateButton)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(dateText2Reader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseDate2Emp))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findReaderByNameButton)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(clearFieldsButton)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(getInfoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
	
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Constants.readersMenu.setVisible(false);
        Constants.mainMenu.setVisible(true);
        Constants.frame.setContentPane(Constants.mainMenu);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO We have to protect against wrong input. Also, maybe complete birthday and stuff.

        String nome, morada, eMail, telefone, bi;

        nome = jTextField2.getText();
        morada = jTextField3.getText();
        bi = jTextField4.getText();
        telefone = jTextField6.getText();
        eMail = jTextField5.getText();
        int [] date = Validation.checkInsertedDate(dateText2Reader.getText(), false);

        if(!nome.equals("") && !morada.equals("") &&  Validation.isInteger(bi)
                && (!telefone.equals("") && Validation.isInteger(telefone) || telefone.equals("")) && date!=null){
            int value = Constants.dbhandler.addPerson(nome, morada, bi, telefone, eMail,date, false, "");

            if (value == 0){
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField6.setText("");
                jTextField5.setText("");
                dateText2Reader.setText("");
                JOptionPane.showMessageDialog(this, "Client added successfully!");
            }
            else if(value == -1)
            {
                JOptionPane.showMessageDialog(this, "There's already a client with such ID Card number!");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Client couldn't be added to the database...");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid Data");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /* Code to GetInfoInReaders

     private void ... {
        String value = ((String)jList1.getSelectedValue());

        if(value!=null){
            clearFieldsButtonActionPerformed(null);
            ArrayList<String> array = Constants.dbhandler.getReaderById(value.split(" ")[2]);
            if(array!=null){
                jTextField2.setText(array.get(0));
                jTextField3.setText(array.get(1));
                dateText2Reader.setText(array.get(2));
                jTextField4.setText(array.get(3));
                jTextField4.setEditable(false);
                jTextField6.setText(array.get(4));
                jTextField5.setText(array.get(5));
            } else {
                JOptionPane.showMessageDialog(this, "Something went wrong. Please contact your support!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must select an employee on the right side!");
        }
            
     }

     Code to cleanFields
     private void...{
            jTextField2.setText("");
            jTextField3.setText("");
            dateText2Reader.setText("  /  /    ");
            jTextField4.setText("");
            jTextField4.setEditable(true);
            jTextField6.setText("");
            jTextField5.setText("");
            ((DefaultListModel) jList1.getModel()).clear();
     }

     *

     code to updateREadersInfo
     private void .... {
 
     * }




     */


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        ArrayList <Person> list = Constants.dbhandler.getPersonsList(false, orderBy, true);

        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();

        for (int i = 0; i < list.size(); i++){
            String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
            model.addElement(info);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void chooseDate1EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDate1EmpActionPerformed
        JFrame date = new JFrame("Choose Date");
        birthReadList = new JCalendar();

        date.getContentPane().add(birthReadList);
        date.pack();
        date.setVisible(true);
        birthReadList.addPropertyChangeListener(this);
    }//GEN-LAST:event_chooseDate1EmpActionPerformed

    private void chooseDate2EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDate2EmpActionPerformed
        JFrame date = new JFrame("Choose Date");
        birthReadMod = new JCalendar();

        date.getContentPane().add(birthReadMod);
        date.pack();
        date.setVisible(true);
        birthReadMod.addPropertyChangeListener(this);
    }//GEN-LAST:event_chooseDate2EmpActionPerformed

    private void dateText1ReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateText1ReaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateText1ReaderActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome, morada, eMail, telefone, bi;

        nome = jTextField2.getText();
        morada = jTextField3.getText();
        bi = jTextField4.getText();
        telefone = jTextField6.getText();
        eMail = jTextField5.getText();

        int [] date = Validation.checkInsertedDate(dateText2Reader.getText(), false);

        if(!nome.equals("") && !morada.equals("") &&  Validation.isInteger(bi)
                        && Validation.isInteger(telefone) && date!=null){
            // same method as in employees so far.
            if(Constants.dbhandler.changePersonData(nome, morada, bi, telefone, eMail, date, false)){
                JOptionPane.showMessageDialog(this, "Changes made successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Something went Wrong");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Data");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsButtonActionPerformed
            jTextField2.setText("");
            jTextField3.setText("");
            dateText2Reader.setText("  /  /    ");
            jTextField4.setText("");
            jTextField4.setEditable(true);
            jTextField6.setText("");
            jTextField5.setText("");
            ((DefaultListModel) jList1.getModel()).clear();
}//GEN-LAST:event_clearFieldsButtonActionPerformed

    private void getInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getInfoButtonActionPerformed
                String value = ((String)jList1.getSelectedValue());

        if(value!=null){
            clearFieldsButtonActionPerformed(null);
            String [] splitted = value.split(" ");
            ArrayList<String> array = Constants.dbhandler.getReaderById(splitted[splitted.length-1]);
            if(array!=null){
                jTextField2.setText(array.get(0));
                jTextField3.setText(array.get(1));
                dateText2Reader.setText(array.get(2));
                jTextField4.setText(array.get(3));
                jTextField4.setEditable(false);
                jTextField6.setText(array.get(4));
                jTextField5.setText(array.get(5));
            } else {
                JOptionPane.showMessageDialog(this, "Something went wrong. Please contact your support!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must select an employee on the right side!");
        }
}//GEN-LAST:event_getInfoButtonActionPerformed

    private void findReaderByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findReaderByNameButtonActionPerformed
        String orderBy;

        orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        ArrayList <Person> list = Constants.dbhandler.findReaderByName(jTextField1.getText(), orderBy);

        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();

        for (int i = 0; i < list.size(); i++){
            String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
            model.addElement(info);
        }
    }//GEN-LAST:event_findReaderByNameButtonActionPerformed

    private void findReaderByDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findReaderByDateButtonActionPerformed
        String orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        int [] date = Validation.checkInsertedDate(dateText1Reader.getText(), false);

          if(date==null){
              JOptionPane.showMessageDialog(this, "Invalid date");
          } else {
            ArrayList <Person> list = Constants.dbhandler.findPersonByBirthDate(date,false,orderBy);

            DefaultListModel model = (DefaultListModel) jList1.getModel();
            model.clear();

            for (int i = 0; i < list.size(); i++){
                String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
                model.addElement(info);
            }
          }
    }//GEN-LAST:event_findReaderByDateButtonActionPerformed

        public void propertyChange(PropertyChangeEvent evt) {
            Object source = evt.getSource();
            Calendar cal;
            GregorianCalendar cal1;
            if (source == birthReadList) {
                    cal = birthReadList.getCalendar();
                    cal1 = new GregorianCalendar(cal.get(Calendar.YEAR),
                                    cal.get(Calendar.MONTH), cal.get(Calendar.DAY_OF_MONTH));
                    dateText1Reader.setText(cal1.get(Calendar.DAY_OF_MONTH) + "/"
                                    + (cal1.get(Calendar.MONTH)+1) + "/"
                                    + cal1.get(Calendar.YEAR));

            } else if (source == birthReadMod) {
                    cal = birthReadMod.getCalendar();
                    cal1 = new GregorianCalendar(cal.get(Calendar.YEAR),
                                    cal.get(Calendar.MONTH), cal.get(Calendar.DAY_OF_MONTH));
                    dateText2Reader.setText(cal1.get(Calendar.DAY_OF_MONTH) + "/"
                                    + (cal1.get(Calendar.MONTH)+1) + "/"
                                    + cal1.get(Calendar.YEAR));
            }
        }

    JCalendar birthReadList;
    JCalendar birthReadMod;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseDate1Emp;
    private javax.swing.JButton chooseDate2Emp;
    private javax.swing.JButton clearFieldsButton;
    private javax.swing.JFormattedTextField dateText1Reader;
    private javax.swing.JFormattedTextField dateText2Reader;
    private javax.swing.JButton findReaderByDateButton;
    private javax.swing.JButton findReaderByNameButton;
    private javax.swing.ButtonGroup genreGroup;
    private javax.swing.JButton getInfoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
