/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reader.java
 *
 * Created on 15/Nov/2010, 15:52:34
 */

package GUI.readers;

import DataStructures.Person;
import com.toedter.calendar.JCalendar;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import librarynetbeans.Constants;
import librarynetbeans.Validation;

/**
 *
 * @author LG
 */
public class Reader extends javax.swing.JPanel implements
			PropertyChangeListener {

    /** Creates new form Reader */
    public Reader() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateText1Reader = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        dateText2Reader = new javax.swing.JFormattedTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        chooseDate1Emp = new javax.swing.JButton();
        chooseDate2Emp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jToggleButton2 = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setText("Find Reader:");
        jPanel1.add(jLabel1);

        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);

        jLabel3.setText("Birthday:");
        jPanel1.add(jLabel3);

        dateText1Reader.setText("   /   /   ");
        dateText1Reader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateText1ReaderActionPerformed(evt);
            }
        });
        jPanel1.add(dateText1Reader);
        jPanel1.add(jTextField1);

        jToggleButton1.setText("Find");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);

        jLabel4.setText("New Reader:");
        jPanel1.add(jLabel4);

        jLabel5.setText("Name:");
        jPanel1.add(jLabel5);

        jLabel6.setText("Address:");
        jPanel1.add(jLabel6);

        jLabel7.setText("Birthday");
        jPanel1.add(jLabel7);

        jLabel9.setText("ID Card Number:");
        jPanel1.add(jLabel9);

        jLabel10.setText("Contact:");
        jPanel1.add(jLabel10);

        jLabel11.setText("E-mail address:");
        jPanel1.add(jLabel11);
        jPanel1.add(jTextField2);
        jPanel1.add(jTextField3);

        dateText2Reader.setText("   /   /   ");
        jPanel1.add(dateText2Reader);
        jPanel1.add(jTextField4);
        jPanel1.add(jTextField5);
        jPanel1.add(jTextField6);

        jList1.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        jButton1.setText("Exclude");
        jPanel1.add(jButton1);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Change Info");
        jPanel1.add(jButton3);

        jButton4.setText("Return");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("List Readers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        chooseDate1Emp.setText("Choose Date");
        chooseDate1Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDate1EmpActionPerformed(evt);
            }
        });
        jPanel1.add(chooseDate1Emp);

        chooseDate2Emp.setText("Choose Date");
        chooseDate2Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDate2EmpActionPerformed(evt);
            }
        });
        jPanel1.add(chooseDate2Emp);

        jLabel12.setText("Order By:");
        jPanel1.add(jLabel12);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "ID" }));
        jPanel1.add(jComboBox1);

        jToggleButton2.setText("Find");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Constants.readersMenu.setVisible(false);
        Constants.mainMenu.setVisible(true);
        Constants.frame.setContentPane(Constants.mainMenu);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO We have to protect against wrong input. Also, maybe complete birthday and stuff.

        String nome, morada, eMail, telefone, bi;

        nome = jTextField2.getText();
        morada = jTextField3.getText();
        bi = jTextField4.getText();
        telefone = jTextField6.getText();
        eMail = jTextField5.getText();
        int [] date = Validation.checkInsertedDate(dateText2Reader.getText(), false);

        if(!nome.equals("") && !morada.equals("") &&  Validation.isInteger(bi)
                && (!telefone.equals("") && Validation.isInteger(telefone) || telefone.equals("")) && date!=null){
                Constants.dbhandler.addPerson(nome, morada, bi, telefone, eMail,date, false);

            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField6.setText("");
            jTextField5.setText("");
            dateText2Reader.setText("");

            JOptionPane.showMessageDialog(this, "Client added Successfully");
        }
        else {
            JOptionPane.showMessageDialog(this, "Invalid Data");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        ArrayList <Person> list = Constants.dbhandler.getPersonsList(false, orderBy);

        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();

        for (int i = 0; i < list.size(); i++){
            String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
            model.addElement(info);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void chooseDate1EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDate1EmpActionPerformed
        JFrame date = new JFrame("Choose Date");
        birthReadList = new JCalendar();

        date.getContentPane().add(birthReadList);
        date.pack();
        date.setVisible(true);
        birthReadList.addPropertyChangeListener(this);
    }//GEN-LAST:event_chooseDate1EmpActionPerformed

    private void chooseDate2EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDate2EmpActionPerformed
        JFrame date = new JFrame("Choose Date");
        birthReadMod = new JCalendar();

        date.getContentPane().add(birthReadMod);
        date.pack();
        date.setVisible(true);
        birthReadMod.addPropertyChangeListener(this);
    }//GEN-LAST:event_chooseDate2EmpActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
                //TODO: Protecções
        String orderBy;

        orderBy = (((String) jComboBox1.getSelectedItem()).equals("Name") ? "nome_pessoa" : "id_pessoa");
        ArrayList <Person> list = Constants.dbhandler.findReaderByName(jTextField1.getText(), orderBy);

        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();

        for (int i = 0; i < list.size(); i++){
            String info = list.get(i).getNome() + " ID: " + list.get(i).getId();
            model.addElement(info);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void dateText1ReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateText1ReaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateText1ReaderActionPerformed

        public void propertyChange(PropertyChangeEvent evt) {
            Object source = evt.getSource();
            Calendar cal;
            GregorianCalendar cal1;
            if (source == birthReadList) {
                    cal = birthReadList.getCalendar();
                    cal1 = new GregorianCalendar(cal.get(Calendar.YEAR),
                                    cal.get(Calendar.MONTH), cal.get(Calendar.DAY_OF_MONTH));
                    dateText1Reader.setText(cal1.get(Calendar.DAY_OF_MONTH) + "/"
                                    + (cal1.get(Calendar.MONTH)+1) + "/"
                                    + cal1.get(Calendar.YEAR));

            } else if (source == birthReadMod) {
                    cal = birthReadMod.getCalendar();
                    cal1 = new GregorianCalendar(cal.get(Calendar.YEAR),
                                    cal.get(Calendar.MONTH), cal.get(Calendar.DAY_OF_MONTH));
                    dateText2Reader.setText(cal1.get(Calendar.DAY_OF_MONTH) + "/"
                                    + (cal1.get(Calendar.MONTH)+1) + "/"
                                    + cal1.get(Calendar.YEAR));
            }
        }

    JCalendar birthReadList;
    JCalendar birthReadMod;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseDate1Emp;
    private javax.swing.JButton chooseDate2Emp;
    private javax.swing.JFormattedTextField dateText1Reader;
    private javax.swing.JFormattedTextField dateText2Reader;
    private javax.swing.ButtonGroup genreGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

}
